/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:db11bc24-e93c-4260-b4cc-0d7e2d1031bf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8NtIZrhLX",
    "aws_user_pools_web_client_id": "3u4l8ccg07qf49j8dt9k92g4c8",
    "oauth": {}
};


export default awsmobile;
